<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '41d8f0178c80ce39f5ce413a6d42c900',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'DATABASE_URL' => 'mysql://u853211615_1JKv8:xyVB45HTX@127.0.0.1:3306/u853211615_G3WCl?serverVersion=8&charset=utf8mb4',
  'MAIL_DRIVER' => 'smtp',
  'MAIL_HOST' => 'smtp.hostinger.com',
  'MAIL_PORT' => '465',
  'MAIL_USERNAME' => 'contact@therapeute-mikoff.fr',
  'MAIL_PASSWORD' => 'xyVb47!6BD',
  'MAIL_ENCRIPTION' => 'tls',
  'MAILER_DSN' => 'smtp://contact@therapeute-mikoff.fr:xyVb47!6BD@smtp.hostinger.com:465',
);

